sfdx-source/Modules/auction/objects/AuctionItem__c/AuctionItem__c.object-meta.xml
<CustomObject>
    <label>Auction Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Auction Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/Modules/auction/objects/AuctionItem__c/fields/Attribution__c.field-meta.xml
<CustomField>
    <fullName>Attribution__c</fullName>
    <label>Attribution</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/Modules/auction/objects/AuctionItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the Auction Item.</description>
    <inlineHelpText>Enter a description of the Auction Item.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdx-source/Modules/auction/classes/AuctionItemController.cls
public class AuctionItemController {

    // Id of the event related to this auction.
    public Id theEventId {public set;}
    
    
    // List of auction items related to this auction.
    public List<AuctionItem__c> items;
    
    

	    
    
    public AuctionItemController() {}
    
    
    public List<AuctionItem__c> getItems() {
        return [SELECT Id, Name, Attribution__c, Description__c FROM AuctionItem__c];
        // return null;
    }
    
    
}